'use strict';

// prettier-ignore
const months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];

const form = document.querySelector('.form');
const containerWorkouts = document.querySelector('.workouts');
const inputType = document.querySelector('.form__input--type');
const inputDistance = document.querySelector('.form__input--distance');
const inputDuration = document.querySelector('.form__input--duration');
const inputCadence = document.querySelector('.form__input--cadence');
const inputElevation = document.querySelector('.form__input--elevation');

// basic geolocation API - takes 2 callbacks
// navigator.geolocation.getCurrentPosition(function(){},function(){})

if (navigator.geolocation)
    navigator.geolocation.getCurrentPosition(
        function(position){
            const { latitude } = position.coords;
            const { longitude } = position.coords;
            // console.log(latitude)
            // console.log(longitude)
            // console.log(`https://www.google.com/maps/@${latitude},@${longitude}`)

            const coords = [ latitude, longitude ]

            const map = L.map('map').setView(coords, 13); // 'map' is id of map element in html

            L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
                attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
            }).addTo(map);
            
            // to get lat/long of click event, so marker can be generated at clicked location
            map.on('click', function(mapEvent) { // here, "map" is special object generated by Leaflet, result of calling L.map(); L is namespace created by Leaflet; using .on instead of .addEventListener
                console.log(mapEvent) // {originalEvent: PointerEvent, containerPoint: p, layerPoint: p, latlng: v, type: 'click', …}
                const { lat, lng } = mapEvent.latlng

                L.marker([ lat, lng ])
                    .addTo(map) // replaced hard-codes with "coords" array
                    .bindPopup(L.popup({
                        maxWidth: 250,
                        minWidth: 100,
                        autoClose: false,
                        closeOnClick: false,
                        className: 'running-popup',

                    },)) // binds popup to marker; can use object instead of string
                    .setPopupContent("Workout")
                    .openPopup();
            }) 
                        
        },

        function(){
            console.log("Unable to find location")
        }
    )
    
    
    
    
    
    
    
// // generates marker at clicked location
    // L.marker(lat, long).addTo(map) // replaced hard-codes with "coords" array
    //     .bindPopup('A pretty CSS popup.<br> Easily customizable.')
    //     .openPopup();

// Leaflet sample code to 1. create map; 2. add tiles; 3. add marker
    // const map = L.map('map').setView([latitude, longitude], 13);

    // L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
    //     attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
    // }).addTo(map);

    // L.marker([51.5, -0.09]).addTo(map)
    //     .bindPopup('A pretty CSS popup.<br> Easily customizable.')
    //     .openPopup();
